name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run unit tests
        run: |
          cd build
          ctest --output-on-failure

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create executable
        run: |
          cd build
          cp TicTacToe /path/to/deployment/directory/TicTacToe

      - name: Run the executable
        run: |
          /path/to/deployment/directory/TicTacToe &
